### ISSUE TITLE
How exactly it works

### ISSUE THREAD

**Issue by amitaryan000** [meabed/Groupon-Clone-On-Magento#1]
Salam,

Today, I downloaded Groupon Clone application of yours from Github.

I saw an Vendor name folder it.
Can you please help me how to configure vendor management to magento since I'm not an developer?

Kindly, let me know if in case it might be time consuming for you to help in this matter. It's Ok! But anyhow I wait for your response.

It will help me a lot if this Vendor module solves my biggest tension.

Thanks in Advance
Amit Gupta

**Comment by meabed** [comment]
Sorry i haven't had much time to write some details on how to but I will post detailed how to soon.
